---
- name: Upgrade Plex
  hosts: yum
  become: yes

  tasks:
    - name: Ensure needs-restarting is installed
      yum:
        name: 'yum-utils'
        state: latest

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Check if reboot is required
      command: needs-restarting -r
      ignore_errors: True
      register: rhel_reboot_required

    - name: Reboot if necessary
      reboot:
        msg: "Reboot initiated by Ansible Upgrade"
      when: rhel_reboot_required.rc == 1


- name: Upgrade apt servers
  hosts: apt
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if necessary
      reboot:
      when: reboot_required.stat.exists
